---
title: "CRISRP-Lambda statistical analysis"
author: "Matteo Ciciani"
date: "2024-07-16"
output: html_document
---

# Read data

```{r, , message=FALSE}
library(ggplot2)
library(tidyr)
library(dplyr)
```

```{r, message=FALSE}
fig1c <- tibble(read.csv('fig_1c_melted.csv'))
fig1e <- tibble(read.csv('fig_1e_melted.csv'))
fig1f <- tibble(read.csv('fig_1f_melted.csv'))

fig2b <- tibble(read.csv('Fig_2b_melted.csv'))

fig2e <- tibble(read.csv('EGFP_pileup_AF_melted.tsv', sep='\t'))
figS3b <- tibble(read.csv('EGFP_pileup_raw_AF_melted.tsv', sep='\t'))

fig4d <- tibble(read.csv('SPIKE_pileup_AF_melted.tsv', sep='\t'))
figS6b <- tibble(read.csv('SPIKE_pileup_raw_AF_melted.tsv', sep='\t'))
```

## Fig. 1c

```{r}
fig1c_a1_aov <- aov(value ~ Tool, data=fig1c %>% filter(variable=='sgRNA_a1'))
summary(fig1c_a1_aov)
```

```{r}
TukeyHSD(fig1c_a1_aov)
```

```{r}
fig1c_2S_aov <- aov(value ~ Tool, data=fig1c %>% filter(variable=='sgRNA_b1'))
summary(fig1c_2S_aov)
```

```{r}
TukeyHSD(fig1c_2S_aov)
```

## Fig. 1e

```{r}
fig1e <- fig1e %>% mutate(guide=sapply(variable, function(x) gsub('\\+.2', '', x)))
```

```{r}
fig1e_a1_aov <- aov(value ~ Tool * variable, data=fig1e %>% filter(guide=='sgRNA_a1'))
summary(fig1e_a1_aov)
```

```{r}
TukeyHSD(fig1e_a1_aov, 'Tool:variable')
```

```{r}
fig1e_b1_aov <- aov(value ~ Tool * variable, data=fig1e %>% filter(guide=='sgRNA_b1'))
summary(fig1e_b1_aov)
```

```{r}
TukeyHSD(fig1e_b1_aov, 'Tool:variable')
```

## Fig. 1f

```{r}
fig1f <- fig1f %>% mutate(guide=sapply(variable, function(x) gsub('\\+.2', '', x)))
```

```{r}
fig1f_a1_aov <- aov(value ~ Tool * variable, data=fig1f %>% filter(guide=='sgRNA_a1'))
summary(fig1f_a1_aov)
```

```{r}
TukeyHSD(fig1f_a1_aov, 'Tool:variable')
```

```{r}
fig1f_b1_aov <- aov(value ~ Tool * variable, data=fig1f %>% filter(guide=='sgRNA_b1'))
summary(fig1f_b1_aov)
```

```{r}
TukeyHSD(fig1f_b1_aov, 'Tool:variable')
```

## Figure 2c

```{r}
fig2b <- fig2b %>% filter(guide!='NT sgRNA')
fig2b_aov <- aov(value ~ Target * guide, data=fig2b)
summary(fig2b_aov)
```

```{r}
TukeyHSD(fig2b_aov, 'Target:guide')
```
## Figure 2f

```{r}
fig2e_1 <- fig2e %>% filter(Guide == 'a1')
t_res <- t.test(AF ~ Sample, data=fig2e_1)
p_1 <- t_res$p.value
t_res
```

```{r}
fig2e_1B <- fig2e %>% filter(Guide == 'a1+a2')
t_res <- t.test(AF ~ Sample, data=fig2e_1B)
p_1B <- t_res$p.value
t_res
```

```{r}
p.adjust(c(p_1, p_1B), method='bonferroni')
```


## Supplementary Figure 3b

```{r}
figS3b_1 <- figS3b %>% filter(Guide == 'a1')
t_res <- t.test(AF ~ Sample, data=figS3b_1)
p_1 <- t_res$p.value
t_res
```

```{r}
figS3b_1B <- figS3b  %>% filter(Guide == 'a1+a2')
t_res <- t.test(AF ~ Sample, data=figS3b_1B)
p_1B <- t_res$p.value
t_res
```

```{r}
p.adjust(c(p_1, p_1B), method='bonferroni')
```

## Figure 4d

```{r}
fig4d_aov <- aov(AF ~ Sample, data=fig4d)
summary(fig4d_aov)
```

```{r}
TukeyHSD(fig4d_aov)
```

## Supplementary Figure 7b

```{r}
figS6b_aov <- aov(AF ~ Sample, data=figS6b)
summary(figS6b_aov)
```

```{r}
TukeyHSD(figS6b_aov)
```


